/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import codigos.Cliente;
import codigos.GerenciamentoSistema;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author raque
 */
public class TelaUserLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaUserLogin.class.getName());
    private GerenciamentoSistema gerenciamento;

    /**
     * Creates new form TelaUserLogin
     */
    public TelaUserLogin() {
       
        this.gerenciamento = GerenciamentoSistema.getInstance();
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(630,466);
    }
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botao_entrarLogin;

        if (botao_entrarLogin != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_cadastreAgora;
        if (botao_cadastreAgora != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botaoVoltar;
        if (botaoVoltar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        campoLogin_LoginUser = new javax.swing.JTextField();
        botao_entrarLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botao_cadastreAgora = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoSenha_LoginUser = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 70, 19);

        campoLogin_LoginUser.setForeground(new java.awt.Color(102, 102, 102));
        campoLogin_LoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLogin_LoginUserActionPerformed(evt);
            }
        });
        getContentPane().add(campoLogin_LoginUser);
        campoLogin_LoginUser.setBounds(70, 170, 180, 30);

        botao_entrarLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_entrarLogin.setForeground(new java.awt.Color(51, 51, 51));
        botao_entrarLogin.setText("Entrar");
        botao_entrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_entrarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_entrarLoginMouseExited(evt);
            }
        });
        botao_entrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(botao_entrarLogin);
        botao_entrarLogin.setBounds(120, 280, 72, 23);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Ainda não possui cadastro?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 320, 158, 30);

        botao_cadastreAgora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_cadastreAgora.setForeground(new java.awt.Color(153, 153, 153));
        botao_cadastreAgora.setText("Cadastre-se agora");
        botao_cadastreAgora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao_cadastreAgora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_cadastreAgoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_cadastreAgoraMouseExited(evt);
            }
        });
        botao_cadastreAgora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastreAgoraActionPerformed(evt);
            }
        });
        getContentPane().add(botao_cadastreAgora);
        botao_cadastreAgora.setBounds(100, 350, 110, 23);

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AgeAcad+");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 50, 320, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ima_pessoasExer.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 20, 385, 570);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Senha");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 210, 70, 19);

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon voltarATT.png"))); // NOI18N
        botaoVoltar.setBorder(null);
        botaoVoltar.setBorderPainted(false);
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseEntered(evt);
            }
        });
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(10, 10, 31, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-410, -80, 730, 300);
        getContentPane().add(campoSenha_LoginUser);
        campoSenha_LoginUser.setBounds(70, 240, 180, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 200, 340, 1110);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, -40, 460, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cadastreAgoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastreAgoraActionPerformed
        new TelaCadastroUsuario().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botao_cadastreAgoraActionPerformed

    private void campoLogin_LoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLogin_LoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLogin_LoginUserActionPerformed

    private void botao_entrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarLoginActionPerformed
        
    String login = campoLogin_LoginUser.getText().trim();
    char[] senhaChar = campoSenha_LoginUser.getPassword();
    String senha = new String(senhaChar);
    java.util.Arrays.fill(senhaChar, '\0');

    if (login.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Preencha todos os campos!",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    Cliente clienteLogado = gerenciamento.loginCliente(login, senha);

    if (clienteLogado != null) {
        new TelaMenuUsuario(clienteLogado).setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(
            this,
            "Login ou senha inválidos",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
        campoSenha_LoginUser.setText("");
  
    }


    }//GEN-LAST:event_botao_entrarLoginActionPerformed

    private void botao_entrarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_entrarLoginMouseEntered
        botao_entrarLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_entrarLogin.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_entrarLoginMouseEntered

    private void botao_entrarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_entrarLoginMouseExited
        botao_entrarLogin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_entrarLoginMouseExited

    private void botao_cadastreAgoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadastreAgoraMouseEntered
        botao_cadastreAgora.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_cadastreAgora.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_cadastreAgoraMouseEntered

    private void botao_cadastreAgoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadastreAgoraMouseExited
        botao_cadastreAgora.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_cadastreAgoraMouseExited

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseEntered
        botaoVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botaoVoltarMouseEntered

    /**
     * @param args the command line arguments
     */
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botao_cadastreAgora;
    private javax.swing.JButton botao_entrarLogin;
    private javax.swing.JTextField campoLogin_LoginUser;
    private javax.swing.JPasswordField campoSenha_LoginUser;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
