/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import codigos.Academia;
import codigos.GerenciamentoSistema;

/**
 *
 * @author maria
 */
public class TelaMenuAcademia extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuAcademia.class.getName());
    private Academia academia;
    private GerenciamentoSistema gerenciamento;
    
    /**
     * Creates new form TelaMenuAcademia
     */
    public TelaMenuAcademia(Academia academia) {
        this.gerenciamento = GerenciamentoSistema.getInstance();
        this.academia = academia;  // SE POR ACASO Dê ERRADO, FOI POR CAUSA DISSO
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(620,440);
    }
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botao_atualizar;

        if (botao_atualizar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_remover;
        if (botao_remover != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
                
        
        botao = botao_fechar;
        if (botao_fechar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_add;
        if (botao_add != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_listar;
        if (botao_listar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botao_fechar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botao_buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        campoID_busca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botao_remover = new javax.swing.JButton();
        botao_atualizar = new javax.swing.JButton();
        botao_add = new javax.swing.JButton();
        botao_listar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 214, 0, 0);

        botao_fechar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon sair.png"))); // NOI18N
        botao_fechar.setBorder(null);
        botao_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_fecharMouseEntered(evt);
            }
        });
        botao_fechar.addActionListener(this::botao_fecharActionPerformed);
        getContentPane().add(botao_fechar);
        botao_fechar.setBounds(560, 30, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil nino (1).png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, 40, 150, 120);

        botao_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/luoa (1).png"))); // NOI18N
        botao_buscar.setBorder(null);
        botao_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_buscarMouseEntered(evt);
            }
        });
        botao_buscar.addActionListener(this::botao_buscarActionPerformed);
        getContentPane().add(botao_buscar);
        botao_buscar.setBounds(450, 120, 40, 40);

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("AgeAcad+");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 20, 610, 70);

        campoID_busca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        getContentPane().add(campoID_busca);
        campoID_busca.setBounds(150, 120, 290, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buscar Academia (informe o nome)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 100, 290, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 610, 10);

        botao_remover.setBackground(new java.awt.Color(0, 204, 255));
        botao_remover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_remover.setText("Remover");
        botao_remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_removerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_removerMouseExited(evt);
            }
        });
        botao_remover.addActionListener(this::botao_removerActionPerformed);
        getContentPane().add(botao_remover);
        botao_remover.setBounds(310, 260, 130, 40);

        botao_atualizar.setBackground(new java.awt.Color(0, 204, 255));
        botao_atualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_atualizar.setText("Atualizar");
        botao_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_atualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_atualizarMouseExited(evt);
            }
        });
        botao_atualizar.addActionListener(this::botao_atualizarActionPerformed);
        getContentPane().add(botao_atualizar);
        botao_atualizar.setBounds(310, 200, 130, 40);

        botao_add.setBackground(new java.awt.Color(0, 204, 255));
        botao_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_add.setText("Cadastrar");
        botao_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_addMouseExited(evt);
            }
        });
        botao_add.addActionListener(this::botao_addActionPerformed);
        getContentPane().add(botao_add);
        botao_add.setBounds(160, 200, 130, 40);

        botao_listar.setBackground(new java.awt.Color(0, 204, 255));
        botao_listar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_listar.setText("Listar Academias");
        botao_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_listarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_listarMouseExited(evt);
            }
        });
        botao_listar.addActionListener(this::botao_listarActionPerformed);
        getContentPane().add(botao_listar);
        botao_listar.setBounds(160, 260, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -80, 620, 420);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versão do sistema: v1.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 380, 600, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, 340, 650, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_fecharMouseEntered
        botao_fechar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_fecharMouseEntered

    private void botao_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecharActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair da conta?");
        if (resposta == 0) {
            setVisible(false);
            TelaInicial janela = new TelaInicial();
            janela.setVisible(true);
        }

    }//GEN-LAST:event_botao_fecharActionPerformed

    private void botao_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_buscarMouseEntered
        botao_buscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_buscarMouseEntered

    private void botao_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_buscarActionPerformed
        // buscar
        String nomeAcad = campoID_busca.getText();

        academia = gerenciamento.buscarAcademia(nomeAcad);

        if (academia != null) {
            JOptionPane.showMessageDialog(null, "Academia Encontrada!\n"+academia.toString(), "Buscar Academia", JOptionPane.QUESTION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Academia não encontrada!\n", "Buscar Academia", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botao_buscarActionPerformed

    private void botao_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_removerActionPerformed
        setVisible(false);
        TelaBuscarAcad_remover janela = new TelaBuscarAcad_remover(academia);
        janela.setVisible(true);
    }//GEN-LAST:event_botao_removerActionPerformed

    private void botao_atualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_atualizarMouseEntered
        botao_atualizar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_atualizar.setBackground(new Color(204,255,0));        
    }//GEN-LAST:event_botao_atualizarMouseEntered

    private void botao_atualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_atualizarMouseExited
        botao_atualizar.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_atualizarMouseExited

    private void botao_removerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_removerMouseEntered
        botao_remover.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_remover.setBackground(new Color(204,255,0)); 
    }//GEN-LAST:event_botao_removerMouseEntered

    private void botao_removerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_removerMouseExited
        botao_remover.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_removerMouseExited

    private void botao_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_atualizarActionPerformed
        setVisible(false);
        TelaBuscarAcad_atualizar janela = new TelaBuscarAcad_atualizar();
        janela.setVisible(true);
    }//GEN-LAST:event_botao_atualizarActionPerformed

    private void botao_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_addActionPerformed
        TelaCadastroAcademia janela = new TelaCadastroAcademia();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_addActionPerformed

    private void botao_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_addMouseEntered
        botao_add.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_add.setBackground(new Color(204,255,0));          
    }//GEN-LAST:event_botao_addMouseEntered

    private void botao_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_addMouseExited
        botao_add.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_addMouseExited

    private void botao_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_listarActionPerformed

            JOptionPane.showMessageDialog(
            this,
            "Listagem das Academias:\n" + gerenciamento.listarAcademias(),
            "Listagem",
            JOptionPane.INFORMATION_MESSAGE);
        

    }//GEN-LAST:event_botao_listarActionPerformed

    private void botao_listarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_listarMouseEntered
        botao_listar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_listar.setBackground(new Color(204,255,0));  
    }//GEN-LAST:event_botao_listarMouseEntered

    private void botao_listarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_listarMouseExited
        botao_listar.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_listarMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_add;
    private javax.swing.JButton botao_atualizar;
    private javax.swing.JButton botao_buscar;
    private javax.swing.JButton botao_fechar;
    private javax.swing.JButton botao_listar;
    private javax.swing.JButton botao_remover;
    private javax.swing.JTextField campoID_busca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
