/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import codigos.GerenciamentoSistema;
import codigos.Academia;
import codigos.Cliente;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;


/**
 *
 * @author maria
 */
public class TelaMatricula extends javax.swing.JFrame {
    
    private Academia academia;
    private GerenciamentoSistema gerenciamento;
    private Cliente clienteLogado;

    /**
     * Creates new form TelaMatricula
     */
    public TelaMatricula(Academia academia, Cliente cliente) {  // ou será que é clientwe
       if (academia == null) {
            throw new IllegalArgumentException("Academia inválida para matrícula");
        }

        this.gerenciamento = GerenciamentoSistema.getInstance();
        this.academia = academia;
        this.clienteLogado = clienteLogado;

        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();

        carregarDadosAcademia();
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(620,440);
    }
       private void carregarDadosAcademia() {
    textoNome.setText(academia.getNome());
    textoPreco.setText("R$ " + academia.getMensalidade());
    textoAvaliacao.setText(String.valueOf(academia.getAvaliacao()));
    textoAtividadesOfer.setText(academia.getAtividadesOfertadas());

    textoNome.setEditable(false);
    textoPreco.setEditable(false);
    textoAvaliacao.setEditable(false);
    textoAtividadesOfer.setEditable(false);
}
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botao_matricular;
 
        botao = botao_matricular;
        if (botao_fechar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_voltar;
        if (botao_voltar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botao_matricular = new javax.swing.JButton();
        botao_voltar = new javax.swing.JButton();
        textoAvaliacao = new javax.swing.JTextField();
        textoNome = new javax.swing.JTextField();
        textoPreco = new javax.swing.JTextField();
        textoAtividadesOfer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botao_fechar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconFechar.png"))); // NOI18N
        botao_fechar.setBorder(null);
        botao_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_fecharMouseEntered(evt);
            }
        });
        botao_fechar.addActionListener(this::botao_fecharActionPerformed);
        getContentPane().add(botao_fechar);
        botao_fechar.setBounds(560, 30, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil bianca (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 40, 150, 120);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AgeAcad+");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 20, 610, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 610, 10);

        botao_matricular.setBackground(new java.awt.Color(204, 255, 0));
        botao_matricular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_matricular.setText("Matricular");
        botao_matricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_matricularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_matricularMouseExited(evt);
            }
        });
        botao_matricular.addActionListener(this::botao_matricularActionPerformed);
        getContentPane().add(botao_matricular);
        botao_matricular.setBounds(250, 310, 100, 30);

        botao_voltar.setText("Voltar");
        botao_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        botao_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_voltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_voltarMouseExited(evt);
            }
        });
        botao_voltar.addActionListener(this::botao_voltarActionPerformed);
        getContentPane().add(botao_voltar);
        botao_voltar.setBounds(30, 170, 100, 30);

        textoAvaliacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoAvaliacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Avaliação"));
        textoAvaliacao.addActionListener(this::textoAvaliacaoActionPerformed);
        getContentPane().add(textoAvaliacao);
        textoAvaliacao.setBounds(300, 190, 110, 40);

        textoNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        textoNome.addActionListener(this::textoNomeActionPerformed);
        getContentPane().add(textoNome);
        textoNome.setBounds(190, 130, 220, 50);

        textoPreco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoPreco.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço"));
        textoPreco.addActionListener(this::textoPrecoActionPerformed);
        getContentPane().add(textoPreco);
        textoPreco.setBounds(190, 190, 100, 40);

        textoAtividadesOfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoAtividadesOfer.setBorder(javax.swing.BorderFactory.createTitledBorder("Atividades Ofertadas"));
        textoAtividadesOfer.addActionListener(this::textoAtividadesOferActionPerformed);
        getContentPane().add(textoAtividadesOfer);
        textoAtividadesOfer.setBounds(190, 250, 220, 50);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versão do sistema: v1.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 380, 600, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, 370, 650, 50);

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações da Academia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 100, 270, 260);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MUJER-_1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 10, 390, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -80, 630, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_fecharMouseEntered
        botao_fechar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_fecharMouseEntered

    private void botao_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecharActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair da conta?");
        if (resposta == 0) {
            new TelaInicial().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botao_fecharActionPerformed

    private void botao_matricularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_matricularMouseEntered
        botao_matricular.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_matricular.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_matricularMouseEntered

    private void botao_matricularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_matricularMouseExited
        botao_matricular.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_matricularMouseExited

    private void botao_matricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_matricularActionPerformed

        // Supondo que você tenha acesso ao cliente logado
        Cliente clienteAtual = gerenciamento.getClienteLogado();
        if (clienteAtual == null) {
            JOptionPane.showMessageDialog(null, "Você precisa estar logado!");
            return;
        }

        // Pedir senha para confirmar
        String senhaConfirmacao = JOptionPane.showInputDialog(
            null, 
            "Digite sua senha para confirmar a matrícula:"
        );

        if (senhaConfirmacao == null || senhaConfirmacao.isEmpty()) {
            return; // Usuário cancelou
        }

        // Chamar matrícula com verificação de senha
        boolean sucesso = gerenciamento.matricularUsuario(academia, clienteAtual, senhaConfirmacao);
        new TelaMenuUsuario(clienteLogado).setVisible(true);
        this.dispose();
    


    }//GEN-LAST:event_botao_matricularActionPerformed

    private void botao_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseEntered
        botao_voltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_voltar.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_voltarMouseEntered

    private void botao_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseExited
        botao_voltar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_voltarMouseExited

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        new TelaMenuUsuario(clienteLogado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_voltarActionPerformed

    private void textoAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAvaliacaoActionPerformed

    private void textoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeActionPerformed

    private void textoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPrecoActionPerformed

    private void textoAtividadesOferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAtividadesOferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAtividadesOferActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_fechar;
    private javax.swing.JButton botao_matricular;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textoAtividadesOfer;
    private javax.swing.JTextField textoAvaliacao;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoPreco;
    // End of variables declaration//GEN-END:variables
}
