/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import codigos.GerenciamentoSistema;
import codigos.Academia;
import codigos.Cliente;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.awt.Color;
import telas.TelaMenuUsuario;

/**
 *
 * @author maria
 */
public class TelaBuscarCli_avaliar extends javax.swing.JFrame {
    
    private GerenciamentoSistema gerenciamento;
    private Academia academia;
    private Cliente clienteLogado;
    
    /**
     * Creates new form TelaBuscarID_avaliar
     */
    public TelaBuscarCli_avaliar(Academia academia, Cliente clienteLogado) {
        
       
        this.gerenciamento = GerenciamentoSistema.getInstance();
        this.academia = academia;
        this.clienteLogado = clienteLogado;
        initComponents();
        botao_confirmaAvaliar.setEnabled(false);
        campoNota.setEnabled(false);
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(620,440);
    }
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botao_confirmaAvaliar;

        if (botao_confirmaAvaliar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao_confirmaAvaliar.setBorderPainted(false);
            botao.setFocusPainted(false);    
        }
        
        botao = botao_fechar;
        if (botao_fechar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao_fechar.setBorderPainted(false);
            botao.setFocusPainted(false);    
        }
        
        botao = botao_voltar;
        if (botao_voltar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao_voltar.setBorderPainted(false);
            botao.setFocusPainted(false);    
        }
        
        botao = botao_OK;
        if (botao_OK != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao_OK.setBorderPainted(false);
            botao.setFocusPainted(false);           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        botao_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botao_OK = new javax.swing.JButton();
        botao_voltar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        campoID_avaliarAcad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        botao_confirmaAvaliar = new javax.swing.JButton();
        campoNota = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botao_fechar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon sair.png"))); // NOI18N
        botao_fechar.setBorder(null);
        botao_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_fecharMouseEntered(evt);
            }
        });
        botao_fechar.addActionListener(this::botao_fecharActionPerformed);
        getContentPane().add(botao_fechar);
        botao_fechar.setBounds(560, 30, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil bianca (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 40, 150, 120);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AgeAcad+");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 20, 610, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 610, 10);

        botao_OK.setText("OK");
        botao_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_OKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_OKMouseExited(evt);
            }
        });
        botao_OK.addActionListener(this::botao_OKActionPerformed);
        getContentPane().add(botao_OK);
        botao_OK.setBounds(350, 190, 50, 30);

        botao_voltar.setText("Voltar");
        botao_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        botao_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_voltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_voltarMouseExited(evt);
            }
        });
        botao_voltar.addActionListener(this::botao_voltarActionPerformed);
        getContentPane().add(botao_voltar);
        botao_voltar.setBounds(30, 180, 100, 30);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nome da Academia");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 170, 140, 16);

        campoID_avaliarAcad.addActionListener(this::campoID_avaliarAcadActionPerformed);
        getContentPane().add(campoID_avaliarAcad);
        campoID_avaliarAcad.setBounds(200, 190, 140, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("As notas devem estar entre entre 0.0 e 5.0");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(170, 250, 270, 14);

        botao_confirmaAvaliar.setBackground(new java.awt.Color(204, 255, 0));
        botao_confirmaAvaliar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_confirmaAvaliar.setText("Avaliar");
        botao_confirmaAvaliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_confirmaAvaliarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_confirmaAvaliarMouseExited(evt);
            }
        });
        botao_confirmaAvaliar.addActionListener(this::botao_confirmaAvaliarActionPerformed);
        getContentPane().add(botao_confirmaAvaliar);
        botao_confirmaAvaliar.setBounds(290, 270, 100, 30);

        campoNota.addActionListener(this::campoNotaActionPerformed);
        getContentPane().add(campoNota);
        campoNota.setBounds(210, 270, 60, 30);

        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Avaliação"));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(180, 230, 240, 90);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 2));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(180, 160, 240, 160);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Avaliar");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 110, 240, 50);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versão do sistema: v1.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 380, 600, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, 360, 650, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correndo-pessoa-ao-ar-livre-homem-em-treinamento-esportivo-uniforme-estilo-de-vida-ativo-e-esportes-jovem-sprinter-modelo-e-layout-cartoon-i.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 10, 490, 490);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -80, 600, 440);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 300, 130, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_fecharMouseEntered
        botao_fechar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_fecharMouseEntered

    private void botao_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecharActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair da conta?");
        if (resposta == 0) {
            new TelaInicial().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botao_fecharActionPerformed

    private void botao_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseEntered
        botao_voltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_voltar.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_voltarMouseEntered

    private void botao_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseExited
        botao_voltar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_voltarMouseExited

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        new TelaMenuUsuario(clienteLogado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_voltarActionPerformed

    private void botao_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_OKActionPerformed
        String busca = campoID_avaliarAcad.getText();
        
        if (busca.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio. Informe o nome da academia  que deseja avaliar!", "[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
        } else {
            academia = gerenciamento.buscarAcademia(busca);
            if (academia != null) {
                botao_confirmaAvaliar.setEnabled(true);
                campoNota.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Nenhuma academia encontrada!\n", "Buscar Academia", JOptionPane.ERROR_MESSAGE);
            }
        }

        
    }//GEN-LAST:event_botao_OKActionPerformed

    private void botao_OKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_OKMouseExited
        botao_OK.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_OKMouseExited

    private void botao_OKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_OKMouseEntered
        botao_OK.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_OK.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_OKMouseEntered

    private void campoID_avaliarAcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoID_avaliarAcadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoID_avaliarAcadActionPerformed

    private void campoNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNotaActionPerformed

    private void botao_confirmaAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_confirmaAvaliarActionPerformed
        if (academia == null) {
        JOptionPane.showMessageDialog(
            this,
            "Nenhuma academia selecionada para avaliação.",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    String texto = campoNota.getText();

    if (texto.trim().isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Campo vazio. Informe uma nota!",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    double nota;

    try {
        nota = Double.parseDouble(texto);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Número inválido!");
        return;
    }

    if (nota < 0.0 || nota > 5.0) {
        JOptionPane.showMessageDialog(this, "Nota deve estar entre 0.0 e 5.0!");
        return;
    }

    boolean sucesso = gerenciamento.avaliarAcademia(academia, nota);

    if (sucesso) {
        JOptionPane.showMessageDialog(
            this,
            "Academia avaliada com sucesso!",
            "Avaliação",
            JOptionPane.INFORMATION_MESSAGE
        );

        campoNota.setText("");
        campoID_avaliarAcad.setText("");
        campoNota.setEnabled(false);
        botao_confirmaAvaliar.setEnabled(false);
        academia = null;
        new TelaMenuUsuario(clienteLogado).setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(
            this,
            "Erro ao avaliar academia!",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
    }


           
    }//GEN-LAST:event_botao_confirmaAvaliarActionPerformed

    private void botao_confirmaAvaliarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_confirmaAvaliarMouseEntered
        botao_confirmaAvaliar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_confirmaAvaliar.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_confirmaAvaliarMouseEntered

    private void botao_confirmaAvaliarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_confirmaAvaliarMouseExited
        botao_confirmaAvaliar.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_confirmaAvaliarMouseExited

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_OK;
    private javax.swing.JButton botao_confirmaAvaliar;
    private javax.swing.JButton botao_fechar;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JTextField campoID_avaliarAcad;
    private javax.swing.JTextField campoNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
