/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.Cursor;

import codigos.Academia;
import codigos.GerenciamentoSistema;
import javax.swing.JOptionPane;


/**
 *
 * @author maria
 */
public class TelaBuscarAcad_remover extends javax.swing.JFrame {
    
    private Academia academia;
    private GerenciamentoSistema gerenciamento;
    int busca;
    
    /**
     * Creates new form TelaBuscarID_remover
     */
    public TelaBuscarAcad_remover(Academia academia) {
        
        this.gerenciamento = GerenciamentoSistema.getInstance();
        this.academia = academia;
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(620,440);
    }
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botao_atualizar;

        if (botao_atualizar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_remover;
        if (botao_remover != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }

        
        botao = botao_fechar;
        if (botao_fechar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_voltar;
        if (botao_voltar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_add;
        if (botao_add != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_listar;
        if (botao_listar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoID_removerAcad = new javax.swing.JTextField();
        botao_voltar = new javax.swing.JButton();
        botao_atualizar = new javax.swing.JButton();
        botao_remover = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botao_add = new javax.swing.JButton();
        botao_listar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botao_fechar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon sair.png"))); // NOI18N
        botao_fechar.setBorder(null);
        botao_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_fecharMouseEntered(evt);
            }
        });
        botao_fechar.addActionListener(this::botao_fecharActionPerformed);
        getContentPane().add(botao_fechar);
        botao_fechar.setBounds(560, 30, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil nino (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 40, 150, 120);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AgeAcad+");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 20, 610, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 610, 10);

        campoID_removerAcad.addActionListener(this::campoID_removerAcadActionPerformed);
        getContentPane().add(campoID_removerAcad);
        campoID_removerAcad.setBounds(330, 200, 110, 30);

        botao_voltar.setText("Voltar");
        botao_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        botao_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_voltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_voltarMouseExited(evt);
            }
        });
        botao_voltar.addActionListener(this::botao_voltarActionPerformed);
        getContentPane().add(botao_voltar);
        botao_voltar.setBounds(30, 170, 100, 30);

        botao_atualizar.setBackground(new java.awt.Color(0, 204, 255));
        botao_atualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_atualizar.setText("Atualizar");
        botao_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_atualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_atualizarMouseExited(evt);
            }
        });
        botao_atualizar.addActionListener(this::botao_atualizarActionPerformed);
        getContentPane().add(botao_atualizar);
        botao_atualizar.setBounds(320, 120, 130, 40);

        botao_remover.setBackground(new java.awt.Color(0, 204, 255));
        botao_remover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_remover.setText("Remover");
        botao_remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_removerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_removerMouseExited(evt);
            }
        });
        botao_remover.addActionListener(this::botao_removerActionPerformed);
        getContentPane().add(botao_remover);
        botao_remover.setBounds(320, 240, 130, 40);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nome da Academia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 180, 150, 16);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 2));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(310, 170, 150, 120);

        botao_add.setBackground(new java.awt.Color(0, 204, 255));
        botao_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_add.setText("Cadastrar");
        botao_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_addMouseExited(evt);
            }
        });
        botao_add.addActionListener(this::botao_addActionPerformed);
        getContentPane().add(botao_add);
        botao_add.setBounds(170, 180, 130, 40);

        botao_listar.setBackground(new java.awt.Color(0, 204, 255));
        botao_listar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_listar.setText("Listar");
        botao_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_listarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_listarMouseExited(evt);
            }
        });
        botao_listar.addActionListener(this::botao_listarActionPerformed);
        getContentPane().add(botao_listar);
        botao_listar.setBounds(170, 240, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -80, 620, 420);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versão do sistema: v1.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 380, 600, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, 340, 650, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_fecharMouseEntered
        botao_fechar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_fecharMouseEntered

    private void botao_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecharActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair da conta?");

        if (resposta == 0) {
            setVisible(false);
            TelaInicial janela = new TelaInicial();
            janela.setVisible(true);
        }
    }//GEN-LAST:event_botao_fecharActionPerformed

    private void campoID_removerAcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoID_removerAcadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoID_removerAcadActionPerformed

    private void botao_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseEntered
        botao_voltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_voltar.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_voltarMouseEntered

    private void botao_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseExited
        botao_voltar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_voltarMouseExited

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        new TelaMenuAcademia(academia).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_voltarActionPerformed

    private void botao_atualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_atualizarMouseEntered
        botao_atualizar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_atualizar.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_atualizarMouseEntered

    private void botao_atualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_atualizarMouseExited
        botao_atualizar.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_atualizarMouseExited

    private void botao_removerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_removerMouseEntered
        botao_remover.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_remover.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_removerMouseEntered

    private void botao_removerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_removerMouseExited
        botao_remover.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_removerMouseExited

    private void botao_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_removerActionPerformed
        String nomeAcad = campoID_removerAcad.getText();

        academia = gerenciamento.buscarAcademia(nomeAcad);
        if (academia != null) {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir essa Academia?");
            
            if (resposta == 0) {
                gerenciamento.excluirAcademia(nomeAcad);
                JOptionPane.showMessageDialog(null, "Academia excluida com sucesso!", "Excluir Academia", JOptionPane.QUESTION_MESSAGE);
                new TelaMenuAcademia(academia).setVisible(true);
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Processo de exclusão de academia não foi concluída!", "Excluir Academia", JOptionPane.QUESTION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma academia encontrada!\n", "Excluir Academia", JOptionPane.ERROR_MESSAGE);
            campoID_removerAcad.setText("");
        }
    }//GEN-LAST:event_botao_removerActionPerformed

    private void botao_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_atualizarActionPerformed
        setVisible(false);
        TelaBuscarAcad_atualizar janela = new TelaBuscarAcad_atualizar();
        janela.setVisible(true);
    }//GEN-LAST:event_botao_atualizarActionPerformed

    private void botao_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_addMouseEntered
        botao_add.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_add.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_addMouseEntered

    private void botao_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_addMouseExited
        botao_add.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_addMouseExited

    private void botao_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_addActionPerformed
        TelaCadastroAcademia janela = new TelaCadastroAcademia();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_addActionPerformed

    private void botao_listarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_listarMouseEntered
        botao_listar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_listar.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_listarMouseEntered

    private void botao_listarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_listarMouseExited
        botao_listar.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_listarMouseExited

    private void botao_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_listarActionPerformed
        JOptionPane.showMessageDialog(
            this,
            "Listagem das Academias:\n" + gerenciamento.listarAcademias(),
            "Listagem",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_botao_listarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_add;
    private javax.swing.JButton botao_atualizar;
    private javax.swing.JButton botao_fechar;
    private javax.swing.JButton botao_listar;
    private javax.swing.JButton botao_remover;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JTextField campoID_removerAcad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
