/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import codigos.Academia;
import codigos.Cliente;
import codigos.GerenciamentoSistema;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

//import telas.TelaInicial;


/**
 *
 * @author maria
 */
public class TelaMenuUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuUsuario.class.getName());
    private GerenciamentoSistema gerenciamento;
    private Cliente clienteLogado;
    private Academia academia;
    

    /**
     * Creates new form TelaMenuUsuario
     */

    public TelaMenuUsuario(Cliente clienteLogado) {
      
    this.gerenciamento = GerenciamentoSistema.getInstance();
    this.academia = academia;
    this.clienteLogado = clienteLogado;
    
    
    initComponents();
    ajustarTamanhoJanela();
    setLocationRelativeTo(null);
    configurarBotoesAposInit();
    
    if (clienteLogado != null) {
        this.gerenciamento.setClienteLogado(clienteLogado);
    }
}
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(620,440);
    }
       
    private void configurarBotoesAposInit() {
         javax.swing.JButton[] botoes = {
            botao_listarAcademias,
            botao_matricular,
            botao_avaliar,
            botao_fechar
        };

        for (javax.swing.JButton botao : botoes) {
            if (botao != null) {
                botao.setOpaque(true);
                botao.setContentAreaFilled(true);
                botao.setBorderPainted(false);
                botao.setFocusPainted(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botao_buscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoID_busca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botao_listarAcademias = new javax.swing.JButton();
        botao_matricular = new javax.swing.JButton();
        botao_avaliar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botao_fechar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon sair.png"))); // NOI18N
        botao_fechar.setBorder(null);
        botao_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_fecharMouseEntered(evt);
            }
        });
        botao_fechar.addActionListener(this::botao_fecharActionPerformed);
        getContentPane().add(botao_fechar);
        botao_fechar.setBounds(560, 30, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil bianca (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 40, 150, 120);

        botao_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/luoa (1).png"))); // NOI18N
        botao_buscar.setBorder(null);
        botao_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_buscarMouseEntered(evt);
            }
        });
        botao_buscar.addActionListener(this::botao_buscarActionPerformed);
        getContentPane().add(botao_buscar);
        botao_buscar.setBounds(450, 130, 40, 40);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AgeAcad+");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 20, 610, 70);

        campoID_busca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        getContentPane().add(campoID_busca);
        campoID_busca.setBounds(150, 130, 290, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buscar Academia (informe o nome)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 110, 290, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 610, 10);

        botao_listarAcademias.setBackground(new java.awt.Color(204, 255, 0));
        botao_listarAcademias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_listarAcademias.setText("Listar Academias");
        botao_listarAcademias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_listarAcademiasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_listarAcademiasMouseExited(evt);
            }
        });
        botao_listarAcademias.addActionListener(this::botao_listarAcademiasActionPerformed);
        getContentPane().add(botao_listarAcademias);
        botao_listarAcademias.setBounds(90, 240, 130, 40);

        botao_matricular.setBackground(new java.awt.Color(204, 255, 0));
        botao_matricular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_matricular.setText("Matricular");
        botao_matricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_matricularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_matricularMouseExited(evt);
            }
        });
        botao_matricular.addActionListener(this::botao_matricularActionPerformed);
        getContentPane().add(botao_matricular);
        botao_matricular.setBounds(240, 240, 130, 40);

        botao_avaliar.setBackground(new java.awt.Color(204, 255, 0));
        botao_avaliar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_avaliar.setText("Avaliar Academia");
        botao_avaliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_avaliarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_avaliarMouseExited(evt);
            }
        });
        botao_avaliar.addActionListener(this::botao_avaliarActionPerformed);
        getContentPane().add(botao_avaliar);
        botao_avaliar.setBounds(390, 240, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -80, 620, 420);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versão do sistema: v1.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 370, 600, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, 340, 650, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecharActionPerformed

    int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente sair da conta?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

    if (resposta == JOptionPane.YES_OPTION) {
        gerenciamento.logoutCliente();
        new TelaInicial().setVisible(true);
        this.dispose();
    }
    
    }//GEN-LAST:event_botao_fecharActionPerformed

    private void botao_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_buscarActionPerformed
        // buscar
       
    String busca = campoID_busca.getText().trim();

    if (busca.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Informe o nome da academia!",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    academia = gerenciamento.buscarAcademia(busca);

    if (academia != null) {
        JOptionPane.showMessageDialog(
            this,
            "Academia encontrada:\n" + academia,
            "Buscar Academia",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
            this,
            "Academia não encontrada!",
            "Buscar Academia",
            JOptionPane.ERROR_MESSAGE
        );
        campoID_busca.setText("");
    }


        
    }//GEN-LAST:event_botao_buscarActionPerformed

    private void botao_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_fecharMouseEntered
        botao_fechar.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_botao_fecharMouseEntered

    private void botao_listarAcademiasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_listarAcademiasMouseEntered
        botao_listarAcademias.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_listarAcademias.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_listarAcademiasMouseEntered

    private void botao_matricularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_matricularMouseEntered
        botao_matricular.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_matricular.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_matricularMouseEntered

    private void botao_avaliarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_avaliarMouseEntered
        botao_avaliar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_avaliar.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_avaliarMouseEntered

    private void botao_listarAcademiasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_listarAcademiasMouseExited
        botao_listarAcademias.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_listarAcademiasMouseExited

    private void botao_matricularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_matricularMouseExited
        botao_matricular.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_matricularMouseExited

    private void botao_avaliarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_avaliarMouseExited
        botao_avaliar.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_avaliarMouseExited

    private void botao_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_buscarMouseEntered
         botao_buscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_buscarMouseEntered

    private void botao_listarAcademiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_listarAcademiasActionPerformed
        JOptionPane.showMessageDialog(
            this,
            "Listagem das Academias:\n" + gerenciamento.listarAcademias(),
            "Listagem",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_botao_listarAcademiasActionPerformed

    private void botao_matricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_matricularActionPerformed

        new TelaBuscarCli_matricula(clienteLogado).setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_botao_matricularActionPerformed

    private void botao_avaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_avaliarActionPerformed

        new TelaBuscarCli_avaliar(academia, clienteLogado).setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_botao_avaliarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_avaliar;
    private javax.swing.JButton botao_buscar;
    private javax.swing.JButton botao_fechar;
    private javax.swing.JButton botao_listarAcademias;
    private javax.swing.JButton botao_matricular;
    private javax.swing.JTextField campoID_busca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}