/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import codigos.GerenciamentoSistema;
import telas.TelaAcadLogin;
import telas.TelaUserLogin;

/**
 *
 * @author raque
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    
    private GerenciamentoSistema gerenciamento;
    
    public TelaInicial() {
       
        this.gerenciamento = GerenciamentoSistema.getInstance();
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();
        setResizable(false);
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(630,466);
    }
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botaoUsuario;

        if (botaoUsuario != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botaoAcademia;
        if (botaoAcademia != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_sair;
        if (botao_sair != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoUsuario = new javax.swing.JButton();
        botaoAcademia = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botao_sair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AgeAcad+");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 320, 70);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deseja acessar como:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 160, 320, 30);

        botaoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        botaoUsuario.setText("Usuário");
        botaoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botaoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoUsuarioMouseExited(evt);
            }
        });
        botaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoUsuario);
        botaoUsuario.setBounds(60, 250, 90, 20);

        botaoAcademia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoAcademia.setForeground(new java.awt.Color(51, 51, 51));
        botaoAcademia.setText("Academia");
        botaoAcademia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botaoAcademia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAcademiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAcademiaMouseExited(evt);
            }
        });
        botaoAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcademiaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAcademia);
        botaoAcademia.setBounds(160, 250, 90, 20);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 90, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ima_pessoasExer.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 20, 385, 570);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconUser.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 200, 50, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconAdmin-removebg-preview (1).png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 200, 40, 44);

        botao_sair.setText("Sair");
        botao_sair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botao_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_sairMouseEntered(evt);
            }
        });
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair);
        botao_sair.setBounds(10, 10, 50, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-410, -80, 730, 360);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 280, 340, 1030);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoVerde2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, -40, 570, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUsuarioActionPerformed
        TelaUserLogin janela = new TelaUserLogin();
        janela.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoUsuarioActionPerformed

    private void botaoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoUsuarioMouseEntered
        botaoUsuario.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botaoUsuario.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botaoUsuarioMouseEntered
    private void botaoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoUsuarioMouseExited
        botaoUsuario.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botaoUsuarioMouseExited

    private void botaoAcademiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcademiaMouseEntered
        botaoAcademia.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botaoAcademia.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botaoAcademiaMouseEntered

    private void botaoAcademiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcademiaMouseExited
        botaoAcademia.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botaoAcademiaMouseExited

    private void botaoAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcademiaActionPerformed
//        TelaAcadLogin janela = new TelaAcadLogin(sistema);
//        janela.setLocationRelativeTo(this);
//        janela.setVisible(true);
        new TelaAcadLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoAcademiaActionPerformed

    private void botao_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_sairMouseEntered
        botao_sair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_sairMouseEntered

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
    int resposta = JOptionPane.showConfirmDialog(
        this,
        "Deseja realmente sair do sistema?",
        "Confirmação",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

if (resposta == JOptionPane.YES_OPTION) {
    System.exit(0);
}

    }//GEN-LAST:event_botao_sairActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Windows".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        
        GerenciamentoSistema gerenciamento = GerenciamentoSistema.getInstance();
        new TelaInicial().setVisible(true);

    });

  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAcademia;
    private javax.swing.JButton botaoUsuario;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables


}
