/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import codigos.Cliente;
import codigos.GerenciamentoSistema;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName());
    private GerenciamentoSistema gerenciamento;

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
       this.gerenciamento = GerenciamentoSistema.getInstance();
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotaoAposInit();
    }
    
           private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(630,466);
    }
       
    private void configurarBotaoAposInit() {
        javax.swing.JButton botao = botao_cadastrarUser;
        if (botao_cadastrarUser != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        seta_voltar = new javax.swing.JButton();
        campoNome_user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoIdade_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoCPF_user = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        campoLogin_user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoSenha_user = new javax.swing.JPasswordField();
        botao_cadastrarUser = new javax.swing.JButton();
        campoRM_user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 10, 540, 50);

        seta_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon voltarATT.png"))); // NOI18N
        seta_voltar.setBorder(null);
        seta_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seta_voltarMouseEntered(evt);
            }
        });
        seta_voltar.addActionListener(this::seta_voltarActionPerformed);
        getContentPane().add(seta_voltar);
        seta_voltar.setBounds(20, 20, 30, 30);

        campoNome_user.setForeground(new java.awt.Color(102, 102, 102));
        campoNome_user.setText(" ");
        campoNome_user.addActionListener(this::campoNome_userActionPerformed);
        getContentPane().add(campoNome_user);
        campoNome_user.setBounds(60, 110, 210, 30);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("Nome");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 80, 100, 19);

        campoIdade_user.setForeground(new java.awt.Color(102, 102, 102));
        campoIdade_user.addActionListener(this::campoIdade_userActionPerformed);
        getContentPane().add(campoIdade_user);
        campoIdade_user.setBounds(60, 180, 60, 30);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("Idade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 150, 60, 21);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setText("CPF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 150, 60, 19);

        try {
            campoCPF_user.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campoCPF_user);
        campoCPF_user.setBounds(150, 180, 120, 30);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel10.setText("Login");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 220, 180, 20);

        campoLogin_user.setForeground(new java.awt.Color(102, 102, 102));
        campoLogin_user.addActionListener(this::campoLogin_userActionPerformed);
        getContentPane().add(campoLogin_user);
        campoLogin_user.setBounds(60, 250, 210, 30);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setText("Senha");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 290, 180, 20);
        getContentPane().add(campoSenha_user);
        campoSenha_user.setBounds(60, 320, 210, 30);

        botao_cadastrarUser.setBackground(new java.awt.Color(204, 255, 0));
        botao_cadastrarUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_cadastrarUser.setForeground(new java.awt.Color(51, 51, 51));
        botao_cadastrarUser.setText("Cadastrar");
        botao_cadastrarUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botao_cadastrarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_cadastrarUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_cadastrarUserMouseExited(evt);
            }
        });
        botao_cadastrarUser.addActionListener(this::botao_cadastrarUserActionPerformed);
        getContentPane().add(botao_cadastrarUser);
        botao_cadastrarUser.setBounds(400, 290, 90, 30);

        campoRM_user.setForeground(new java.awt.Color(102, 102, 102));
        campoRM_user.setText(" ");
        campoRM_user.addActionListener(this::campoRM_userActionPerformed);
        getContentPane().add(campoRM_user);
        campoRM_user.setBounds(340, 220, 210, 60);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Se não, digite apenas \"nenhuma\".");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 180, 250, 30);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Se sim, informe quais possui.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 160, 250, 30);

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Você possui comorbidades?");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 130, 250, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadastro_Background.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, 30, 600, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-100, 0, 750, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNome_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNome_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNome_userActionPerformed

    private void campoIdade_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdade_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdade_userActionPerformed

    private void campoLogin_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLogin_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLogin_userActionPerformed

    private void botao_cadastrarUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadastrarUserMouseEntered
        botao_cadastrarUser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_cadastrarUser.setBackground(new Color(113,222,252));
    }//GEN-LAST:event_botao_cadastrarUserMouseEntered

    private void botao_cadastrarUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadastrarUserMouseExited
        botao_cadastrarUser.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_cadastrarUserMouseExited

    private void botao_cadastrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarUserActionPerformed
        String nome = campoNome_user.getText();
        String cpf = campoCPF_user.getText();
        String texto = campoIdade_user.getText();
        int idade;

        String login = campoLogin_user.getText();
        char[] senhaChar = campoSenha_user.getPassword();
        String senha = new String(senhaChar);
        java.util.Arrays.fill(senhaChar, '\0');
        String restMedica = campoRM_user.getText();

        if (nome.trim().isEmpty()
            || cpf.contains(" ")
            || texto.trim().isEmpty()
            || login.trim().isEmpty()
            || senha.trim().isEmpty()
            || restMedica.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Vazio. Por favor, preencha todos os campos!", "[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                idade = Integer.parseInt(campoIdade_user.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Idade inválida!");
                return;
            }
            if (senha.length() < 5) {
                JOptionPane.showMessageDialog(null, "A senha deve ter pelo menos 5 caracteres.", "´[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (idade < 0) {
                JOptionPane.showMessageDialog(null, "Idade inválida!", "[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
            } else if (idade < 15) {
                JOptionPane.showMessageDialog(null, "Você precisa ter pelo menos 16 anos para se cadastrar!", "[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
                setVisible(false);
                TelaUserLogin janela = new TelaUserLogin();
                janela.setVisible(true);
            } else {
                Cliente buscarCliente = gerenciamento.buscarCliente(cpf);
                if (buscarCliente != null){
                    JOptionPane.showMessageDialog(null, "Cliente já cadastrado!", "[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
                    setVisible(false);
                    TelaUserLogin janela = new TelaUserLogin();
                    janela.setVisible(true);
                } else {
                    Cliente c = new Cliente (nome, cpf,idade, login, senha, restMedica);
                    gerenciamento.cadastrarCliente(c);
                    JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");

                    Cliente clienteLogado = GerenciamentoSistema.getInstance().getClienteLogado();

                    setVisible(false);
                    TelaMenuUsuario janela = new TelaMenuUsuario(clienteLogado);
                    janela.setVisible(true);
                }
            }

        }

    }//GEN-LAST:event_botao_cadastrarUserActionPerformed

    private void campoRM_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRM_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRM_userActionPerformed

    private void seta_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seta_voltarActionPerformed
        setVisible(false);
        TelaUserLogin janela = new TelaUserLogin();
        janela.setVisible(true);
    }//GEN-LAST:event_seta_voltarActionPerformed

    private void seta_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seta_voltarMouseEntered
        seta_voltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_seta_voltarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrarUser;
    private javax.swing.JFormattedTextField campoCPF_user;
    private javax.swing.JTextField campoIdade_user;
    private javax.swing.JTextField campoLogin_user;
    private javax.swing.JTextField campoNome_user;
    private javax.swing.JTextField campoRM_user;
    private javax.swing.JPasswordField campoSenha_user;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton seta_voltar;
    // End of variables declaration//GEN-END:variables
}
