/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import codigos.GerenciamentoSistema;
import java.awt.Color;
import java.awt.Cursor;
import codigos.Academia;

/**
 *
 * @author maria
 */
public class TelaAcadLogin extends javax.swing.JFrame {
    
    

    /**
     * Creates new form TelaAcadLogin
     */
    private GerenciamentoSistema gerenciamento;
    private Academia academia;
    
    public TelaAcadLogin() {
        
        this.gerenciamento = GerenciamentoSistema.getInstance();
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();
        
    }

    
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(630,466);
    }
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botao_entrarLogin;

        if (botao_entrarLogin != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        
        botao = botaoVoltar;
        if (botaoVoltar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        campoLogin_acad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoSenha_acad = new javax.swing.JPasswordField();
        botao_entrarLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 70, 19);

        campoLogin_acad.setForeground(new java.awt.Color(102, 102, 102));
        campoLogin_acad.addActionListener(this::campoLogin_acadActionPerformed);
        getContentPane().add(campoLogin_acad);
        campoLogin_acad.setBounds(70, 170, 180, 30);

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AgeAcad+");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 50, 320, 70);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Senha");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 210, 70, 19);

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon voltarATT.png"))); // NOI18N
        botaoVoltar.setBorder(null);
        botaoVoltar.setBorderPainted(false);
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseEntered(evt);
            }
        });
        botaoVoltar.addActionListener(this::botaoVoltarActionPerformed);
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(10, 10, 31, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ima_pessoasExer.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 20, 385, 570);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-410, -80, 730, 300);
        getContentPane().add(campoSenha_acad);
        campoSenha_acad.setBounds(70, 240, 180, 30);

        botao_entrarLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_entrarLogin.setText("Entrar");
        botao_entrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_entrarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_entrarLoginMouseExited(evt);
            }
        });
        botao_entrarLogin.addActionListener(this::botao_entrarLoginActionPerformed);
        getContentPane().add(botao_entrarLogin);
        botao_entrarLogin.setBounds(120, 280, 72, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-20, 210, 340, 1104);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 0, 490, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoLogin_acadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLogin_acadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLogin_acadActionPerformed

    private void botaoVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseEntered
        botaoVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botaoVoltarMouseEntered

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botao_entrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarLoginActionPerformed
        String login = campoLogin_acad.getText();
        char[] senhaChar = campoSenha_acad.getPassword();
        String senha = new String(senhaChar);
        java.util.Arrays.fill(senhaChar, '\0');


    if (login.trim().isEmpty() || senha.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Preencha login e senha!",
            "Erro de login",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean admin = gerenciamento.autenticarAdmin(login, senha);

    if (admin == false) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Login ou senha inválidos!",
            "Erro de login",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } else {
        new TelaMenuAcademia(academia).setVisible(true);
        dispose();
    }
    }//GEN-LAST:event_botao_entrarLoginActionPerformed

    private void botao_entrarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_entrarLoginMouseEntered
        botao_entrarLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_entrarLogin.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_entrarLoginMouseEntered

    private void botao_entrarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_entrarLoginMouseExited
        botao_entrarLogin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_entrarLoginMouseExited

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botao_entrarLogin;
    private javax.swing.JTextField campoLogin_acad;
    private javax.swing.JPasswordField campoSenha_acad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
