/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import codigos.Academia;
import codigos.GerenciamentoSistema;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class TelaCadastroAcademia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroAcademia.class.getName());
    private GerenciamentoSistema gerenciamento;
    private Academia academia;
    /**
     * Creates new form TelaCadastroAcademia
     */
    public TelaCadastroAcademia() {
        this.gerenciamento =  GerenciamentoSistema.getInstance();
        this.academia = academia;
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotaoAposInit();
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(630,466);
    }
       
    private void configurarBotaoAposInit() {
        javax.swing.JButton botao = botao_cadastrarAcad;

        if (botao_cadastrarAcad != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNome_acad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoTelefone_acad = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        campoEndereco_acad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoMensalidade_acad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoQtdPersonais_acad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoAtividadesOfertadas = new javax.swing.JTextField();
        botao_cadastrarAcad = new javax.swing.JButton();
        seta_voltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadastro_Background.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 520, 50);

        campoNome_acad.setForeground(new java.awt.Color(102, 102, 102));
        campoNome_acad.addActionListener(this::campoNome_acadActionPerformed);
        getContentPane().add(campoNome_acad);
        campoNome_acad.setBounds(60, 110, 210, 30);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("Nome");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 80, 70, 19);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel10.setText("Telefone");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 150, 180, 20);

        try {
            campoTelefone_acad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campoTelefone_acad);
        campoTelefone_acad.setBounds(60, 180, 210, 30);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("Endereço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 220, 110, 21);

        campoEndereco_acad.setForeground(new java.awt.Color(102, 102, 102));
        campoEndereco_acad.addActionListener(this::campoEndereco_acadActionPerformed);
        getContentPane().add(campoEndereco_acad);
        campoEndereco_acad.setBounds(60, 250, 210, 30);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setText("Mensalidade R$");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 300, 120, 19);

        campoMensalidade_acad.setForeground(new java.awt.Color(102, 102, 102));
        campoMensalidade_acad.addActionListener(this::campoMensalidade_acadActionPerformed);
        getContentPane().add(campoMensalidade_acad);
        campoMensalidade_acad.setBounds(60, 330, 110, 30);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setText("Personais");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 300, 70, 20);

        campoQtdPersonais_acad.setForeground(new java.awt.Color(102, 102, 102));
        campoQtdPersonais_acad.addActionListener(this::campoQtdPersonais_acadActionPerformed);
        getContentPane().add(campoQtdPersonais_acad);
        campoQtdPersonais_acad.setBounds(200, 330, 70, 30);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Atividades Ofertadas");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 130, 250, 19);

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Se sua academia oferecer qualquer tipo ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 150, 250, 20);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("de atividade, digite embaixo. Se não tiver, ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 170, 250, 16);

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("digite \"nenhum\"");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 190, 250, 16);

        campoAtividadesOfertadas.setForeground(new java.awt.Color(102, 102, 102));
        campoAtividadesOfertadas.setText(" ");
        campoAtividadesOfertadas.addActionListener(this::campoAtividadesOfertadasActionPerformed);
        getContentPane().add(campoAtividadesOfertadas);
        campoAtividadesOfertadas.setBounds(320, 220, 210, 70);

        botao_cadastrarAcad.setBackground(new java.awt.Color(0, 204, 255));
        botao_cadastrarAcad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_cadastrarAcad.setText("Cadastrar");
        botao_cadastrarAcad.setBorder(null);
        botao_cadastrarAcad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_cadastrarAcadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_cadastrarAcadMouseExited(evt);
            }
        });
        botao_cadastrarAcad.addActionListener(this::botao_cadastrarAcadActionPerformed);
        getContentPane().add(botao_cadastrarAcad);
        botao_cadastrarAcad.setBounds(380, 310, 90, 30);

        seta_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon voltarATT.png"))); // NOI18N
        seta_voltar.setBorder(null);
        seta_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seta_voltarMouseEntered(evt);
            }
        });
        seta_voltar.addActionListener(this::seta_voltarActionPerformed);
        getContentPane().add(seta_voltar);
        seta_voltar.setBounds(10, 20, 40, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadastro_Background.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, 30, 590, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNome_acadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNome_acadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNome_acadActionPerformed

    private void campoEndereco_acadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEndereco_acadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEndereco_acadActionPerformed

    private void campoMensalidade_acadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMensalidade_acadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMensalidade_acadActionPerformed

    private void campoQtdPersonais_acadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQtdPersonais_acadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQtdPersonais_acadActionPerformed

    private void campoAtividadesOfertadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAtividadesOfertadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAtividadesOfertadasActionPerformed

    private void botao_cadastrarAcadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadastrarAcadMouseEntered
        botao_cadastrarAcad.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_cadastrarAcad.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_cadastrarAcadMouseEntered

    private void botao_cadastrarAcadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadastrarAcadMouseExited
        botao_cadastrarAcad.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_cadastrarAcadMouseExited

    private void botao_cadastrarAcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarAcadActionPerformed
        String nome = campoNome_acad.getText();
        academia = gerenciamento.buscarAcademia(nome);
        while (academia != null) {
            JOptionPane.showMessageDialog(null, "Já existe uma academia com esse mesmo nome", "´[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
            nome = campoNome_acad.getText();
            academia = gerenciamento.buscarAcademia(nome);
        }

        String telefone = campoTelefone_acad.getText();
        String endereco = campoEndereco_acad.getText();
        String mensal = campoMensalidade_acad.getText();
        Double mensalidade;
        String personais = campoQtdPersonais_acad.getText();
        int qtd_personais;
        String atividadesOfer = campoAtividadesOfertadas.getText();

        if (nome.trim().isEmpty()
            || telefone.trim().isEmpty()
            || endereco.trim().isEmpty()
            || mensal.trim().isEmpty()
            || personais.trim().isEmpty()
            || atividadesOfer.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Vazio. Por favor, preencha todos os campos!", "[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                mensalidade = Double.parseDouble(mensal);
                qtd_personais = Integer.parseInt(personais);
            } catch (NumberFormatException e) {                JOptionPane.showMessageDialog(this, "Valor inválido!", "´[ERROR] Cadastro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            gerenciamento.cadastrarAcademia(nome, endereco, telefone, mensalidade, qtd_personais, atividadesOfer);
            JOptionPane.showMessageDialog(this, "Academia cadastrada com sucesso!");

            setVisible(false);
            TelaMenuAcademia janela = new TelaMenuAcademia(academia);
            janela.setVisible(true);
        }
    }//GEN-LAST:event_botao_cadastrarAcadActionPerformed

    private void seta_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seta_voltarMouseEntered
        seta_voltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_seta_voltarMouseEntered

    private void seta_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seta_voltarActionPerformed
        setVisible(false);
        TelaMenuAcademia janela = new TelaMenuAcademia(academia);
        janela.setVisible(true);
    }//GEN-LAST:event_seta_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroAcademia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrarAcad;
    private javax.swing.JTextField campoAtividadesOfertadas;
    private javax.swing.JTextField campoEndereco_acad;
    private javax.swing.JTextField campoMensalidade_acad;
    private javax.swing.JTextField campoNome_acad;
    private javax.swing.JTextField campoQtdPersonais_acad;
    private javax.swing.JFormattedTextField campoTelefone_acad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton seta_voltar;
    // End of variables declaration//GEN-END:variables
}
