package telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import codigos.Academia;
import codigos.GerenciamentoSistema;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class TelaAtualizar extends javax.swing.JFrame {
    
    private Academia academia;
    private GerenciamentoSistema gerenciamento;
    private String acadPesquisada; // aqui serve para receber o valor da busca da TelaBuscaID_atualizar pra na hora de clicar no botão atualizar, ele saber qual academia é pra atualizar
    /**
     * Creates new form TelaAtualizar
     */
    public TelaAtualizar(Academia academia) { // esse parametro tbm é pra mesma funcionalidade para pegar o valor da busca da TelaBuscaID_atualizar
        if (academia == null) {
            throw new IllegalArgumentException("Academia não pode ser nula");
        }    
        
        this.gerenciamento = GerenciamentoSistema.getInstance();
        this.academia = academia;
        initComponents();
        ajustarTamanhoJanela();
        setLocationRelativeTo(null);
        configurarBotoesAposInit();
        
        campoNome_atua.setText(academia.getNome());
        campoEndereco_atua.setText(academia.getEndereco());
        campoTelefone_atua.setText(academia.getN_contato());
        Double mensalidade = academia.getMensalidade();
        String mensal_texto = String.valueOf(mensalidade);
        campoMensalidade_atua.setText(mensal_texto);
        int num_personais = academia.getNumPersonais();
        String qtd_personais = String.valueOf(num_personais);
        campoPersonais_atua.setText(qtd_personais);
        campoAtividadesOfert_atua.setText(academia.getAtividadesOfertadas());
        
    }
    
       private void ajustarTamanhoJanela() {
        // Define um tamanho fixo
        setSize(620,440);
    }
       
    private void configurarBotoesAposInit() {
        javax.swing.JButton botao = botao_atualizar;

        if (botao_atualizar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        
        botao = botao_fechar;
        if (botao_fechar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
        
        botao = botao_voltar;
        if (botao_voltar != null) {
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
            botao.setBorderPainted(false);
            botao.setFocusPainted(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botao_voltar = new javax.swing.JButton();
        botao_atualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoNome_atua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoPersonais_atua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoEndereco_atua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoTelefone_atua = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        campoMensalidade_atua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoAtividadesOfert_atua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botao_fechar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon sair.png"))); // NOI18N
        botao_fechar.setBorder(null);
        botao_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_fecharMouseEntered(evt);
            }
        });
        botao_fechar.addActionListener(this::botao_fecharActionPerformed);
        getContentPane().add(botao_fechar);
        botao_fechar.setBounds(560, 30, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil nino (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 40, 150, 120);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AgeAcad+");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 20, 610, 70);

        botao_voltar.setText("Voltar");
        botao_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        botao_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_voltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_voltarMouseExited(evt);
            }
        });
        botao_voltar.addActionListener(this::botao_voltarActionPerformed);
        getContentPane().add(botao_voltar);
        botao_voltar.setBounds(470, 110, 100, 30);

        botao_atualizar.setBackground(new java.awt.Color(0, 204, 255));
        botao_atualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_atualizar.setText("Atualizar");
        botao_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_atualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_atualizarMouseExited(evt);
            }
        });
        botao_atualizar.addActionListener(this::botao_atualizarActionPerformed);
        getContentPane().add(botao_atualizar);
        botao_atualizar.setBounds(230, 310, 130, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 180, 70, 20);

        campoNome_atua.addActionListener(this::campoNome_atuaActionPerformed);
        getContentPane().add(campoNome_atua);
        campoNome_atua.setBounds(40, 200, 160, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Personais");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 300, 70, 20);

        campoPersonais_atua.addActionListener(this::campoPersonais_atuaActionPerformed);
        getContentPane().add(campoPersonais_atua);
        campoPersonais_atua.setBounds(40, 320, 160, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Endereço");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 240, 70, 20);

        campoEndereco_atua.addActionListener(this::campoEndereco_atuaActionPerformed);
        getContentPane().add(campoEndereco_atua);
        campoEndereco_atua.setBounds(40, 260, 160, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Telefone");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 180, 150, 20);

        try {
            campoTelefone_atua.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone_atua.addActionListener(this::campoTelefone_atuaActionPerformed);
        getContentPane().add(campoTelefone_atua);
        campoTelefone_atua.setBounds(220, 200, 160, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mensalidade R$");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 240, 110, 20);

        campoMensalidade_atua.addActionListener(this::campoMensalidade_atuaActionPerformed);
        getContentPane().add(campoMensalidade_atua);
        campoMensalidade_atua.setBounds(220, 260, 160, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Atividades Ofertadas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 180, 160, 20);

        campoAtividadesOfert_atua.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoAtividadesOfert_atua.addActionListener(this::campoAtividadesOfert_atuaActionPerformed);
        getContentPane().add(campoAtividadesOfert_atua);
        campoAtividadesOfert_atua.setBounds(410, 210, 160, 90);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 610, 10);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 170, 580, 200);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versão do sistema: v1.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 390, 600, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, 380, 650, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBranco.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -80, 620, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_fecharMouseEntered
        botao_fechar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_fecharMouseEntered

    private void botao_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecharActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair da conta?");

        if (resposta == 0) {
            setVisible(false);
            TelaInicial janela = new TelaInicial();
            janela.setVisible(true);
        }
    }//GEN-LAST:event_botao_fecharActionPerformed

    private void botao_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseEntered
        botao_voltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_voltar.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_voltarMouseEntered

    private void botao_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseExited
        botao_voltar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botao_voltarMouseExited

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        setVisible(false);
        TelaMenuAcademia janela = new TelaMenuAcademia(academia);
        janela.setVisible(true);
    }//GEN-LAST:event_botao_voltarActionPerformed

    private void botao_atualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_atualizarMouseEntered
        botao_atualizar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botao_atualizar.setBackground(new Color(204,255,0));
    }//GEN-LAST:event_botao_atualizarMouseEntered

    private void botao_atualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_atualizarMouseExited
        botao_atualizar.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_botao_atualizarMouseExited

    private void botao_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_atualizarActionPerformed
        String nome = campoNome_atua.getText();
        String endereco = campoEndereco_atua.getText();
        String telefone = campoTelefone_atua.getText();
        String texto = campoMensalidade_atua.getText();
        String atividadesOfertadas = campoAtividadesOfert_atua.getText();
        String texto2 = campoPersonais_atua.getText();

        Double mensalidade;
        int qtd_personais;

        try {
            mensalidade = Double.parseDouble(texto);
            qtd_personais = Integer.parseInt(texto2);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, informe um valor válido", "[ERROR] Atualizar", JOptionPane.ERROR_MESSAGE);
            return;
        }
                
        if ((nome.trim().isEmpty()) || (endereco.trim().isEmpty()) || (telefone.trim().isEmpty()) || (texto.trim().isEmpty()) || (texto2.trim().isEmpty()) || (atividadesOfertadas.trim().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Campo Vazio. Por favor, preencha todos os campos!", "[ERROR] Atualizar", JOptionPane.ERROR_MESSAGE);
        } else {
            
            if (qtd_personais < 0) {
                JOptionPane.showMessageDialog(this, "Por favor, informe um valor válido", "[ERROR] Atualizar", JOptionPane.ERROR_MESSAGE);
            } else {
               // acadPesq = Integer.parseInt(acadPesquisada); // como a busca é por ID, então transformar esse valor em int passando o valor do parametro
               String acadPesq = academia.getNome();
               gerenciamento.atualizarAcademia(acadPesq, nome, endereco, telefone, mensalidade, atividadesOfertadas, qtd_personais);
                JOptionPane.showMessageDialog(null, "Academia "+academia.getNome()+" atualizada com sucesso!");
                setVisible(false);
                TelaMenuAcademia janela = new TelaMenuAcademia(academia);
                janela.setVisible(true);
            }

        }
        
    }//GEN-LAST:event_botao_atualizarActionPerformed

    private void campoNome_atuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNome_atuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNome_atuaActionPerformed

    private void campoPersonais_atuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPersonais_atuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPersonais_atuaActionPerformed

    private void campoAtividadesOfert_atuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAtividadesOfert_atuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAtividadesOfert_atuaActionPerformed

    private void campoMensalidade_atuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMensalidade_atuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMensalidade_atuaActionPerformed

    private void campoTelefone_atuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefone_atuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefone_atuaActionPerformed

    private void campoEndereco_atuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEndereco_atuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEndereco_atuaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_atualizar;
    private javax.swing.JButton botao_fechar;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JTextField campoAtividadesOfert_atua;
    private javax.swing.JTextField campoEndereco_atua;
    private javax.swing.JTextField campoMensalidade_atua;
    private javax.swing.JTextField campoNome_atua;
    private javax.swing.JTextField campoPersonais_atua;
    private javax.swing.JFormattedTextField campoTelefone_atua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
